### ISSUE TITLE
Loading local image 

### ISSUE THREAD

**Issue by TheOska** [Piasy/ShapedDraweeView#3]
Thanks for your great library, I would like to ask how to load local storage image? 

using simply Fresco's SimpleDraweeView, which can successfully be loaded
simpleDraweeView.setImageURI(<local image path>)

However, using ShapedDraweeView, it cannot show the image
shapedDraweeView.setImageURI(<local image path>

so how to solve this problem? Big thx

**Comment by Piasy** [comment]
Just pass a local file uri to `setUri` in code below: 

``` java
ShapedDraweeView shapedDraweeView = (ShapedDraweeView) findViewById(R.id.mShapedDraweeView);
DraweeController controller = Fresco.newDraweeControllerBuilder()
        .setUri(Uri.parse(
                "http://img0.bdstatic.com/img/image/shouye/xinshouye/chongwu16830.jpg"))
        .build();
shapedDraweeView.setController(controller);
```

READ THE README CLOSELY PLEASE.
